In [0]:
import numpy as np
np.__version__

'1.17.3'

In [0]:
# CRIANDO OBJETOS NDARRAY
a = np.array([5,10,30,12,25,2]) 
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) 
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [0]:
# ALGUNS TIPOS DE DADOS DO NUMPY
print(np.int64) # INTEIRO COM SINAL DE 64 BITS (-9223372036854775808 ate 9223372036854775807))
print(np.float32)
print(np.complex)
print(np.bool)
print(np.object)
print(np.string_)

<class 'numpy.int64'>
<class 'numpy.float32'>
<class 'complex'>
<class 'bool'>
<class 'object'>
<class 'numpy.bytes_'>


In [0]:
# NDARRAY DE 0s
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [0]:
# NDARRAY DE 1s
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
# 1D-ARRAY COM VALORES DE 10 A 20, COM PASSOS DE 5
np.arange(10, 30, 5) 

array([10, 15, 20, 25])

In [0]:
# NDARRAY COM 50 Nºs ESPAÇADOS DE 0 A 10
np.linspace(0, 1, 50) 

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [0]:
# NDARRAY DE CONSTANTES
np.full((2, 2), 7) 

array([[7, 7],
       [7, 7]])

In [0]:
# NDARRAY DE UMA MATRIZ IDENTIDADE DE TAMANHO 2
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
# NDARRAY ALEATORIA DE 2 DIMENSÕES
np.random.random((2, 2, 3))

array([[[0.76104584, 0.94641606, 0.47174277],
        [0.92680293, 0.71367626, 0.59826769]],

       [[0.65474787, 0.3073728 , 0.95544112],
        [0.49718361, 0.95144545, 0.24078769]]])

In [0]:
# NDARRAY VAZIA DE 2 DIMENSÕES
np.empty((3,2)) 

array([[1.46100745e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [0]:
# CRIANDO OBJETOS NDARRAY ALEATÓRIO DE 1 DIMENSÃO
x1 = np.random.randint(10, size=5)
x1

array([6, 2, 7, 6, 1])

In [0]:
print(x1)
print("tipo: ", type(x1))
print("dimensões: ", x1.ndim)
print("formato (shape):", x1.shape)
print("tamanho: ", x1.size)
print("tipo dos dados (dtype):", x1.dtype)
print(np.info(x1))

[6 2 7 6 1]
tipo:  <class 'numpy.ndarray'>
dimensões:  1
formato (shape): (5,)
tamanho:  5
tipo dos dados (dtype): int64
None


In [0]:
# CRIANDO OBJETOS NDARRAY ALEATÓRIO DE 2 DIMENSÃO
x2 = np.random.randint(10, size=(3, 4))
x2

array([[6, 7, 2, 5],
       [0, 5, 7, 6],
       [4, 0, 5, 8]])

In [0]:
print(x2)
print("tipo: ", type(x2))
print("dimensões: ", x2.ndim)
print("formato (shape):", x2.shape)
print("tamanho: ", x2.size)
print("tipo dos dados (dtype):", x1.dtype)

[[6 7 2 5]
 [0 5 7 6]
 [4 0 5 8]]
tipo:  <class 'numpy.ndarray'>
dimensões:  2
formato (shape): (3, 4)
tamanho:  12
tipo dos dados (dtype): int64


In [0]:
# CRIANDO OBJETOS NDARRAY ALEATÓRIO DE 3 DIMENSÃO
x3 = np.random.randint(10, size=(3, 4, 5))
x3

array([[[2, 1, 8, 6, 4],
        [0, 1, 0, 6, 3],
        [9, 7, 7, 7, 3],
        [5, 6, 1, 6, 7]],

       [[3, 0, 4, 8, 0],
        [8, 7, 2, 9, 7],
        [5, 7, 5, 5, 6],
        [3, 3, 5, 2, 3]],

       [[6, 9, 7, 4, 8],
        [7, 2, 3, 7, 1],
        [0, 2, 7, 7, 1],
        [4, 9, 9, 4, 5]]])

In [0]:
print(x3)
print("tipo: ", type(x3))
print("dimensões: ", x3.ndim)
print("formato (shape):", x3.shape)
print("tamanho: ", x3.size)
print("tipo dos dados (dtype):", x3.dtype)

[[[2 1 8 6 4]
  [0 1 0 6 3]
  [9 7 7 7 3]
  [5 6 1 6 7]]

 [[3 0 4 8 0]
  [8 7 2 9 7]
  [5 7 5 5 6]
  [3 3 5 2 3]]

 [[6 9 7 4 8]
  [7 2 3 7 1]
  [0 2 7 7 1]
  [4 9 9 4 5]]]
tipo:  <class 'numpy.ndarray'>
dimensões:  3
formato (shape): (3, 4, 5)
tamanho:  60
tipo dos dados (dtype): int64


In [0]:
# COMPARAÇÃO LÓGICO ELEMENTE POR ELEMENTO
a < 25

array([ True,  True,  True, False, False])

In [0]:
# SOMA ACUMULADA
x3.cumsum()

array([  2,   3,  11,  17,  21,  21,  22,  22,  28,  31,  40,  47,  54,
        61,  64,  69,  75,  76,  82,  89,  92,  92,  96, 104, 104, 112,
       119, 121, 130, 137, 142, 149, 154, 159, 165, 168, 171, 176, 178,
       181, 187, 196, 203, 207, 215, 222, 224, 227, 234, 235, 235, 237,
       244, 251, 252, 256, 265, 274, 278, 283])

In [0]:
# ANTES DE ORDERNAR a
a

array([ 5, 10, 30, 12, 25])

In [0]:
# ORDENAÇÃO DE ELEMENTOS
a.sort()

In [0]:
# DEPOIS DE ORDENAR a
a

array([ 5, 10, 12, 25, 30])

In [0]:
# INSERE ELEMENTO NO FINAL
np.append(a, 20)

array([ 5, 10, 30, 12, 25,  2, 20])

In [0]:
# INSERE ELEMENTO 2 NA POSIÇÃO 0
np.insert(a, 0, 2)

array([ 2,  5, 10, 30, 12, 25,  2])

In [0]:
# DELETE O PRIMEIRO ELEMENTO 2
np.delete(a, 2)

array([ 5, 10, 12, 25,  2])